# Generated by Django 2.0 on 2017-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondata',
            name='actions',
            field=models.CharField(choices=[('/data/apple.csv', 'apple'), ('TOTAL', 'total')], max_length=49),
        ),
    ]
