# Generated by Django 2.0 on 2017-12-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0002_auto_20171227_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicateurs',
            name='strategyuser',
        ),
        migrations.AddField(
            model_name='indicateurs',
            name='strategyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='algobourso.StrategyUser'),
        ),
    ]
