# Generated by Django 2.0 on 2017-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0002_auto_20171228_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondata',
            name='ligneportefeuille',
        ),
        migrations.RemoveField(
            model_name='actiondata',
            name='strategyuser',
        ),
        migrations.AddField(
            model_name='strategyuser',
            name='actions',
            field=models.ManyToManyField(to='algobourso.ActionData'),
        ),
    ]
