# Generated by Django 2.0 on 2017-12-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0003_auto_20171228_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sma',
            name='indicateurs',
        ),
        migrations.AddField(
            model_name='sma',
            name='indicateurs',
            field=models.ManyToManyField(to='algobourso.Indicateurs'),
        ),
    ]
