# Generated by Django 2.0 on 2017-12-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0004_auto_20171227_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyuser',
            old_name='nom',
            new_name='stratname',
        ),
    ]
