# Generated by Django 2.0 on 2017-12-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0006_auto_20171228_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondata',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='actiondata',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='actiondata',
            name='setcash',
        ),
        migrations.RemoveField(
            model_name='actiondata',
            name='stratname',
        ),
    ]
