# Generated by Django 2.0 on 2017-12-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0007_auto_20171228_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicateurs',
            name='strategyuser',
        ),
        migrations.RenameField(
            model_name='strategyuser',
            old_name='stratname',
            new_name='strategy_name',
        ),
        migrations.RemoveField(
            model_name='sma',
            name='indicateurs',
        ),
        migrations.AddField(
            model_name='sma',
            name='strategyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='algobourso.StrategyUser'),
        ),
        migrations.AddField(
            model_name='strategyuser',
            name='signal_dachat',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='strategyuser',
            name='signal_rachat',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='strategyuser',
            name='signal_vad',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='strategyuser',
            name='signal_vente',
            field=models.BooleanField(default='0'),
        ),
        migrations.DeleteModel(
            name='Indicateurs',
        ),
    ]
