# Generated by Django 2.0 on 2017-12-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0008_auto_20171228_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyuser',
            name='signal_dachat',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='strategyuser',
            name='signal_rachat',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='strategyuser',
            name='signal_vad',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='strategyuser',
            name='signal_vente',
            field=models.BooleanField(default=0),
        ),
    ]
