# Generated by Django 2.0 on 2017-12-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0011_auto_20171228_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sma',
            name='strategyuser',
        ),
        migrations.AddField(
            model_name='strategyuser',
            name='sma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='algobourso.sma'),
        ),
    ]
