# Generated by Django 2.0 on 2017-12-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algobourso', '0012_auto_20171228_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sma',
            name='close_less_sma',
            field=models.NullBooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='sma',
            name='close_over_sma',
            field=models.NullBooleanField(default=0),
        ),
    ]
